#fup que leia um numero inteiro e faça sua tabuada
n = int(input('digite um número para exibir sua tabuada: '))
print('{}'.format(n*1))
print('{}'.format(n*2))
print('{}'.format(n*3))
print('{}'.format(n*4))
print('{}'.format(n*5))
print('{}'.format(n*6))
print('{}'.format(n*7))
print('{}'.format(n*8))
print('{}'.format(n*9))
print('{}'.format(n*10))
